environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    Libpng_repo: "http://github.com/glennrp/libpng-releases"
  matrix:
  - configuration: release
  - configuration: debug
  
platform:
  - x86
  - amd64

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Get libpng source from GIT
  - appveyor DownloadFile %Libpng_repo%/raw/master/lpng1634.7z
  - 7z x lpng1634.7z
  - mkdir zlib
  - cd zlib
  - appveyor DownloadFile https://github.com/maxirmx/Dist_zlib/releases/latest/download/zlib-%platform%-%configuration%.7z
  - 7z e zlib.7z
  - cd ..
   
build_script:                                                                                   
  # Build
  - cd lpng1634   
  - nmake -f scripts/makefile.vcwin32
  - cd ..
  - mkdir d
  - mkdir d\include
  - mkdir d\lib
  - copy lpng1634\scripts\pnglibconf.h.prebuilt  d\include\pnglibconf.h
  - copy lpng1634\png.h d\include
  - copy lpng1634\pngconf.h d\include
  - copy lpng1634\pnginfo.h d\include
  - copy lpng1634\libpng.lib d\lib
  - cd d
  - 7z a -r -y ..\libpng-%platform%-%configuration%.7z *.*
   
test: off

artifacts:
   - path: libpng-%platform%-%configuration%.7z
   
deploy:
- provider: GitHub
  release: $(appveyor_build_version)
  description: 'libpng build [$(appveyor_build_version)]'
  auth_token:
    secure: 7fz/vsEpOOUyPYNmrykrY4lgqu3XQsag6g4x25nOwtd2dM2kc3X3GPoPzMCMDno/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: false       # deploy on tag push only
