environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    libpng_repo: "https://github.com/glennrp/libpng"
    libpng_version: "v1.6.37"
  matrix:
  - configuration: release
  - configuration: debug
  
platform:
  - x86
  - amd64

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Submodules
  - git submodule init
  - git submodule update
  # Get libpng source from GIT
  - git clone -q --branch=%libpng_version% %libpng_repo% libpng
  # Get zlib
  - ps: ./EZTools/load-library.ps1 "zlib" $env:platform $env:configuration
  
build_script:                                                                                   
  # Build
  - build.cmd %platform% %configuration%   

after_build:
  - mkdir d
  - mkdir d\include
  - mkdir d\lib
  - copy libpng\scripts\pnglibconf.h.prebuilt  d\include\pnglibconf.h
  - copy libpng\png.h d\include
  - copy libpng\pngconf.h d\include
  - copy libpng\pnginfo.h d\include
  - copy libpng\libpng.lib d\lib
  - cd d
  - 7z a -tzip -r -y ..\libpng-%platform%-%configuration%.zip *.*
   
test: off

artifacts:
   - path: libpng-%platform%-%configuration%.zip
   
deploy:
- provider: GitHub
# I am tagging through github
# Tag format is v<major version>.<minor version>, shall be consistent with major.minor of Appveyor build
# release: v$(appveyor_build_version)
  description: 'libpng AppVeyor build script [$(appveyor_build_version)] with binaries'
  auth_token:
    secure: 7fz/vsEpOOUyPYNmrykrY4lgqu3XQsag6g4x25nOwtd2dM2kc3X3GPoPzMCMDno/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
