environment:
  global:
    VisualStudio: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    Libpng_repo: "http://github.com/glennrp/libpng-releases"

platform:
  - x86
  # amd64

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Get libpng source from GIT
  - appveyor DownloadFile %Libpng_repo%/raw/master/lpng1623.7z
  - 7z x lpng1623.7z
  - mkdir zlib
  - cd zlib
  - appveyor DownloadFile "http://ci.appveyor.com/api/projects/maxirmx/Dist-zlib/artifacts/zlib.7z?job=platform:+x86"
  - 7z e zlib.7z
  - cd ..
   
build_script:                                                                                   
  # Build
  - echo %platform%
  - cd lpng1623   
  - nmake -f scripts/makefile.vcwin32
  - cd ..
  - mkdir d
  - mkdir d\include
  - mkdir d\lib
  - copy lpng1623\png.h d\include
  - copy lpng1623\pngconf.h d\include
  - copy lpng1623\pnginfo.h d\include
  - copy lpng1623\libpng.lib d\lib
  - cd d
  - 7z a -r -y ..\libpng.7z *.*
   
test: off

artifacts:
   - path: libpng.7z
